name: "build api-rest"
run-name: "build api-rest"
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
      - name: "Configurar QEMU"
        uses: docker/setup-qemu-action@v2
      - name: "Configurar Docker"
        uses: docker/setup-buildx-action@v2
      - name: "Configurar credenciales AWS"
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}
      - name: "Autenticar en AWS ECR"
        id: login-ecr-publico
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public
      - name: "Build and push"
        env:
          ECR_REGISTRY: ${{ steps.login-ecr-publico.outputs.registry }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          environment:
            DB_HOST: ${{ }}
            DB_NAME: ${{ }}
            DB_PASSWORD: ${{ }}
            DB_USER: ${{ }}
            DORY_WEB_APP_URL: ${{ }}
            GOOGLE_PASSWORD_APP: ${{ }}
            URL_LOGO: ${{ }}
            OAUTH_CLIENT_ID_MOBILE: ${{ }}
            OAUTH_CLIENT_ID_WEB: ${{ }}
          push: true
          tags: ${{ env.ECR_REGISTRY }}/${{ vars.AWS_REGISTRY_ALIAS }}/${{ vars.AWS_REPOSITORY }}:latest

